### ISSUE TITLE
Colors are off

### ISSUE THREAD

**Issue by mfozz** [Garsondee/RTSControls#11]
The destination color settings don't adjust for me (stuck at opaque green) and the line is there whether the option is selected or not.
I'm testing the module in D&D 2.4.1 in the Forge and 3.0.1 in my desktop Electron app.

<img width="537" alt="Screenshot 2024-02-17 at 10 29 28 AM" src="https://github.com/Garsondee/RTSControls/assets/89781047/b22055b1-cfa6-4978-a94f-1d5c642bf603">
<img width="193" alt="Screenshot 2024-02-17 at 10 37 13 AM" src="https://github.com/Garsondee/RTSControls/assets/89781047/98cd5a25-7726-474f-a493-050b3d0fc2bb">

**Comment by Garsondee** [comment]
I think this is fixed now.

 https://github.com/Garsondee/RTSControls/releases/tag/1.2.2
