### ISSUE TITLE
[Bug] Install button in Foundry Modules List doesn't work

### ISSUE THREAD

**Issue by ChasarooniZ** [Garsondee/RTSControls#3]
![image](https://github.com/Garsondee/RTSControls/assets/79132112/923fe92f-b66b-466f-bf08-695b28a55df2)

**Comment by Garsondee** [comment]
Strange! I will investigate.

**Comment by Garsondee** [comment]
Temporarily I've changed the JSON link - checked it locally and it seemed to work.

**Comment by Garsondee** [comment]
I think it's fixed now.
