### ISSUE TITLE
Right Clicking Tokens

### ISSUE THREAD

**Issue by insquared** [Garsondee/RTSControls#6]
Whenever I would right-click tokens while having token(s) selected, as a GM, to add them to initiative/enter combat state (or to do other stuff such as apply conditions) it would instead move all the selected tokens to that area, due to opening the token tooltip menu also requiring a right-click.

It would be great if when it detects a token it doesn’t move, similar to how it detects panning.

**Comment by Garsondee** [comment]
Fixed!
