### ISSUE TITLE
Feature req: Delete movement on pause

### ISSUE THREAD

**Issue by Hvitball** [Garsondee/RTSControls#7]
First: awesome stuff, thanks! 
An option to delete movement/not resume movement after pause would be really useful.
Managed to do it with some macros, but a bit plundersome.

**Comment by Garsondee** [comment]
Done. Version 1.0.10 released now.

**Comment by Hvitball** [comment]
Awesome work man, thank you! Just had a little horror-themed game with lots of rooms and narrow hallways to explore, and Monks active tiles to trigger pauses when they stepped into a room where something happened. This module made it feel really cool when exploring! 
Couldn't get it to work with elevation, so ended up putting different levels on different maps, but still was a literal game changer! Thank you!
