### ISSUE TITLE
Add option to make movement command triggered by Shift-Right Click

### ISSUE THREAD

**Issue by buttonpushertv** [Garsondee/RTSControls#8]
Would it be possible to add an option that performs the movement when you use Shift & Right Click?

Right Clicking is a heavily used function and erroneous clicks cause all sorts of mayhem with tokens moving all over the place as people forget that right click no longer just moves the view on the map. If Shift & Right Click could be optionally set to be the movement command, that would greatly reduce mine and my player's frustration.

An option in the settings would be a great addition to this unique module. Thanks!

**Comment by Garsondee** [comment]
1.0.11 has the option now.
