### ISSUE TITLE
"drawing not found" errors

### ISSUE THREAD

**Issue by nschoenwald** [Garsondee/RTSControls#9]
I just tried out the module because the idea seems great, however I get multiple of those errors when I move multiple tokens (six in my case) in a gridded scene:
<img width="1063" alt="image" src="https://github.com/Garsondee/RTSControls/assets/72390280/a44f424b-14e1-4b64-9ccb-d671127fd78a">

Using current versions of foundry, dnd5e and this module. All other modules (except routinglib) are deactivated for testing purposes.

**Comment by Garsondee** [comment]
A very strange error - it doesn't exist in a local foundry install but appears when I load up Foundry through Forge. I'm investigating.

**Comment by nschoenwald** [comment]
Interesting! I'm hosting on Oracle Cloud, for what it's worth.

**Comment by Garsondee** [comment]
> Interesting! I'm hosting on Oracle Cloud, for what it's worth.

That is extremely helpful actually! What is strange is that it produces the error but the drawings are deleted correctly. Very strange and unhelpful but I'll try and get it sorted one way or the other ASAP.

**Comment by Garsondee** [comment]
I think I've fixed it.

https://github.com/Garsondee/RTSControls/releases/download/1.2.1/module.json
